apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-cfg
  namespace: spark-apps  # Specify the namespace if not default
data:
  metastore-site.xml: |
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgres.spark-apps:5432/hive_metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>GUYgsjsj@123</value>  # Consider using a Kubernetes Secret for this value
      </property>
      <property>
        <name>metastore.warehouse.dir</name>
        <value>s3a://delta/</value>
      </property>
      <property>
        <name>metastore.thrift.port</name>
        <value>9083</value>
      </property>
    </configuration>
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>http://host.docker.internal:9000</value>
      </property>
      <property>
        <name>fs.s3a.fast.upload</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.s3a.access.key</name>
        <value>minioadmin</value>  # Consider using a Kubernetes Secret for this value
      </property>
      <property>
        <name>fs.s3a.secret.key</name>
        <value>minioadmin</value>  # Consider using a Kubernetes Secret for this value
      </property>
    </configuration>