apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: spark-apps
  labels:
    group: db
data:
  POSTGRES_DB: hive_metastore
  POSTGRES_USER: hive
  POSTGRES_PASSWORD: GUYgsjsj@123