name: Deploy Milan to K3s Local

on: push  # Simplified trigger for local testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          mkdir -p $HOME/.kube

      - name: Configure kubectl
        run: |
          echo "$KUBE_CONFIG" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Install Helm manually
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash          

      - name: Create namespace spark-apps
        run: |
          kubectl create namespace spark-apps || echo "Namespace spark-apps already exists"

      - name: Create namespace airflow
        run: |
          kubectl create namespace airflow || echo "Namespace spark-apps already exists"    

      - name: Create namespace Spark Operator
        run: |
          kubectl create namespace spark-operator || echo "Namespace spark-operator already exists"  

      - name: Create namespace trino
        run: |
          kubectl create namespace trino || echo "Namespace trino already exists"    

      - name: Create namespace kafka
        run: |
          kubectl create namespace kafka || echo "Namespace kafka already exists"    

      - name: Create namespace dbt
        run: |
          kubectl create namespace dbt || echo "Namespace dbt already exists" 

      - name: Create namespace superset
        run: |
          kubectl create namespace superset || echo "Namespace superset already exists"            

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'  # Specify a version if needed

      - name: Create ClusterRoleBinding
        run: |
          kubectl apply -f spark8s/spark_svc_account.yaml -n spark-apps

      - name: Install Spark Operator
        run: |
          helm upgrade --install osds-release spark8s/spark-operator-1.1.27/spark-operator \
            -n spark-operator \
            --create-namespace \
            --wait \
            --timeout 2m


      - name: Apply Postgres for Hive
        run: |
          kubectl apply -f spark8s/postgres/postgres-config.yaml -f spark8s/postgres/postgres-config-pvc-svc-statefulset.yaml -n spark-apps

      - name: Apply Hive Metastore Configurations
        run: |
          kubectl apply -f spark8s/hive-metastore/hive-metastore-cgf.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-metastore.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-metastore-svc.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-schema.yaml -n spark-apps    

      - name: Add Trino Helm repository
        run: |
          helm repo add trino https://trinodb.github.io/charts
          helm repo update

      - name: Install Spark Thrift Server
        run: |
          kubectl apply -f spark8s/spark-thriftserver.yaml -n spark-apps           

      - name: Install Trino
        run: |
          helm upgrade --install --values trino/values.yaml trino trino/trino -n trino    
