name: Deploy Milan to Local Minikube

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          mkdir -p $HOME/.kube

      - name: Configure kubectl
        run: |
          minikube kubectl -- config view --minify > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl cluster-info

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Create namespaces
        run: |
          for ns in spark-apps airflow spark-operator trino kafka dbt superset; do
            kubectl create namespace $ns || echo "Namespace $ns already exists"
          done

      - name: Enable Minikube addons
        run: |
          minikube addons enable storage-provisioner
          minikube addons enable default-storageclass

      - name: Wait for storage class
        run: |
          kubectl wait --for=condition=Available storageclass/standard --timeout=60s

      - name: Create ClusterRoleBinding
        run: |
          kubectl apply -f spark8s/spark_svc_account.yaml -n spark-apps

      - name: Install Spark Operator
        run: |
          helm upgrade --install osds-release spark8s/spark-operator-1.1.27/spark-operator \
            -n spark-operator \
            --create-namespace \
            --wait \
            --timeout 2m

      - name: Apply Postgres for Hive
        run: |
          kubectl apply -f spark8s/postgres/postgres-config.yaml -n spark-apps
          kubectl apply -f spark8s/postgres/postgres-config-pvc-svc-statefulset.yaml -n spark-apps
          kubectl wait --for=condition=ready pod -l app=postgres -n spark-apps --timeout=120s

      - name: Apply Hive Metastore Configurations
        run: |
          kubectl apply -f spark8s/hive-metastore/hive-metastore-cgf.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-metastore.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-metastore-svc.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-schema.yaml -n spark-apps
          kubectl wait --for=condition=ready pod -l app=hive-metastore -n spark-apps --timeout=180s

      - name: Add and Update Helm Repositories
        run: |
          helm repo add trino https://trinodb.github.io/charts
          helm repo update

      - name: Install Spark Thrift Server
        run: |
          kubectl apply -f spark8s/spark-thriftserver.yaml -n spark-apps
          kubectl wait --for=condition=ready pod -l app=spark-thrift-server -n spark-apps --timeout=180s

      - name: Install Trino
        run: |
          helm upgrade --install --values trino/values.yaml trino trino/trino -n trino --wait

      - name: Verify Deployments
        run: |
          echo "Checking pod status across all namespaces..."
          kubectl get pods --all-namespaces
          echo "Checking services..."
          kubectl get services --all-namespaces
          echo "Checking persistent volumes..."
          kubectl get pv,pvc --all-namespaces
